### ISSUE TITLE
好精彩的融合算法

### ISSUE THREAD

**Issue by Nanming666** [DrHoisu/Channel_Mixer_Layer#1]
你好，有幸能看到你的成果，我感觉这个融合算法在气象领域会有很大的前景，我是研究短临降水的，因为预测降水的时候不单单是一个通道就能完成的，起码两个通道以上了。我也很想尝试这个算法在短临的应用。

**Comment by DrHoisu** [comment]
Thank you for your praise to our work. Currently, our proposed Channel Mixer Layer only supports space weather dataset for the ionosphere, and does not support meteorological precipitation datasets for the atmosphere. We welcome developers to contribute more dataset support

感谢您对我们工作的支持，目前我们提出的Channel Mixer Layer仅仅支持电离层的空间天气数据集，大气层的气象降水数据集并不支持。我们欢迎开发者贡献更多的数据集支持。
