### ISSUE TITLE
Problems with visualization

### ISSUE THREAD

**Issue by Nanming666** [DrHoisu/Channel_Mixer_Layer#2]
(VMRNN) (base) ~/cui/cf/Channel_Mixer_Layer-main$ python tools/visualizations/vis_video.py -d iono -w work_dirs/iono/simvp/mix_16channel --index 125 --save_dirs visualization/iono/simvp/mix_16channel/
/home/hgx/cui/cf/OpenSTL-OpenSTL-Lightning/openstl/datasets/dataloader_human.py:6: UserWarning: import flash_attn failed and set torch.disable_flash_attn True
  import torch
Traceback (most recent call last):
  File "/home/hgx/cui/cf/Channel_Mixer_Layer-main/tools/visualizations/vis_video.py", line 151, in <module>
    main()
  File "/home/hgx/cui/cf/Channel_Mixer_Layer-main/tools/visualizations/vis_video.py", line 54, in main
    config.update(dataset_parameters[args.dataname])
KeyError: 'iono'

**Comment by DrHoisu** [comment]
Thank you for using our program. 
I notice that (VMRNN) (base) in the first line means you use virtual environment, but you didn't activate it
So try to use command: conda activate Mixer

Meanwhile I notice that /home/hgx/cui/cf/OpenSTL-OpenSTL-Lightning/openstl/datasets/dataloader_human.py:6:
The OpenSTL-Lightning means your environment contains pytorch-lightning version OpenSTL, it will conflict with pytorch version OpenSTL used in our program. So please make sure you have a clean environment.

**Comment by Nanming666** [comment]
Thank you for your patience in replying, the problem was successfully solved

**Comment by Nanming666** [comment]
Next I will try the application of this method to precipitation prediction
